### ISSUE TITLE
Camera is not working

### ISSUE THREAD

**Issue by 0312birdzhang** [sailfish-on-ginkgo/droid-config-ginkgo#2]

**Comment by 0312birdzhang** [comment]
strace -Ff -s1024 -e file -o gst-inspect.strace gst-inspect-1.0 --gst-disable-segtrap --gst-disable-registry-fork droidcamsrc : 
https://gist.github.com/0312birdzhang/0278a7e224f6d9744f2ac49871a680c5

**Comment by 0312birdzhang** [comment]
TODO, use https://github.com/AndroidBlobs/vendor_xiaomi_ginkgo

**Comment by 0312birdzhang** [comment]
```
[defaultuser@RedmiNote8 ~]$ eu-stack -e /usr/bin/gst-inspect-1.0 --core /var/coredumps/core-gst-inspect-1.0-5214-1724067871
PID 5214 - core
TID 5214:
#0  0x000000743639c124
sailfish-on-ginkgo/main#13  0x000000743696e4e8
sailfish-on-ginkgo/droid-config-ginkgo#2  0x0000007437314544 call_function(char const*, void (*)(int, char**, char**), char const*) [clone .part.0]
sailfish-on-ginkgo/droid-config-ginkgo#3  0x0000007436aef648
eu-stack: dwfl_thread_getframes tid 5214 at 0x7436aef647 in <unknown>: address out of range
```

**How to make core dump files**
```
ulimit -c unlimited
echo "/var/coredumps/core-%e-%p-%t" | tee /proc/sys/kernel/core_pattern
mkdir -p /var/coredumps
chmod 1777 /var/coredumps
gst-inspect-1.0 --gst-disable-segtrap --gst-disable-registry-fork droidcamsrc

```

**Comment by 0312birdzhang** [comment]
gdb /usr/bin/gst-inspect-1.0 /var/coredumps/core-gst-inspect-1.0-5214-1724067871

```
(gdb) bt
#0  0x000000743639c124 in ?? ()
sailfish-on-ginkgo/main#13  0x0000007437314724 in call_function (realpath=0x852ce90 "/usr/libexec/droid-hybris/system/lib64/libstagefright.so", function=<optimized out>, function_name=0x7437326f48 "function") at linker_soinfo.cpp:372
sailfish-on-ginkgo/droid-config-ginkgo#2  call_array<void (*)(int, char**, char**)> (array_name=0x852ce90 "/usr/libexec/droid-hybris/system/lib64/libstagefright.so", functions=0x852e988, count=<optimized out>, 
    realpath=0x852ce90 "/usr/libexec/droid-hybris/system/lib64/libstagefright.so", reverse=false) at linker_soinfo.cpp:413
sailfish-on-ginkgo/droid-config-ginkgo#3  0x0000007437314724 in call_function (realpath=0x2 <error: Cannot access memory at address 0x2>, function=<optimized out>, function_name=0x7437326f48 "function") at linker_soinfo.cpp:372
sailfish-on-ginkgo/droid-config-ginkgo#4  call_array<void (*)(int, char**, char**)> (array_name=0x7437327148 "DT_INIT_ARRAY", functions=0x7436aef648, count=<optimized out>, realpath=0x2 <error: Cannot access memory at address 0x2>, reverse=false)
    at linker_soinfo.cpp:413
sailfish-on-ginkgo/main#10  0x0000007437278010 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by 0312birdzhang** [comment]
after enable selinux, gst-inspect logs: https://gist.github.com/0312birdzhang/bdc44d150959e3e63bca219094e4e697

**Comment by Michal-Szczepaniak** [comment]
I had the same issue on my oneplus 6(t) on hybris 16.0 base, and this patch, which will be merged to hybris-patches on later date, fixes it 

https://github.com/mer-hybris/hybris-patches/pull/31

**Comment by 0312birdzhang** [comment]
![254095cbc313ba0dc6cebfd1e85487b0](https://github.com/user-attachments/assets/2677e5ef-29f9-45da-b617-bf27e95c6fd5)
